version: '3.9'

services:
  pg:
    image: bitnami/postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignite-gym
