name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - edited

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  e2e-tests:
    if: github.event.pull_request.merged == true
    name: E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: ignite-gym
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          PORT: 3333
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/ignite-gym?schema=public"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
