name: Pipeline

on: [push]

jobs:
  unit-e2e:
    name: Unit and E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: ignite-gym
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit and E2E Tests
        run: npm run test
        env:
          PORT: 3333
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/ignite-gym?schema=public"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
